# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create(oid: 12001, name:"Additions & Remodeling")
Category.create(oid: 12002, name:"Air Conditioning")
Category.create(oid: 12003, name:"Appliances")
Category.create(oid: 12004, name:"Appraiser")
Category.create(oid: 12005, name:"Architects & Engineers")
Category.create(oid: 15213, name:"Art & Mirror Mounting")
Category.create(oid: 12006, name:"Audio/Visual & Computers")
Category.create(oid: 12007, name:"Awnings")
Category.create(oid: 12008, name:"Brick & Stone")
Category.create(oid: 12009, name:"Cabinets")
Category.create(oid: 12010, name:"Carpenters")
Category.create(oid: 12011, name:"Carpet & Upholstery Cleaning")
Category.create(oid: 12012, name:"Ceilings")
Category.create(oid: 12013, name:"Central Vacuum")
Category.create(oid: 12014, name:"Cleaning & Maid Services")
Category.create(oid: 12015, name:"Concrete")
Category.create(oid: 12016, name:"Countertops")
Category.create(oid: 12017, name:"Decks")
Category.create(oid: 12018, name:"Demolition Service")
Category.create(oid: 12019, name:"Designers & Decorators")
Category.create(oid: 12020, name:"Developer")
Category.create(oid: 12021, name:"Disability Services")
Category.create(oid: 12022, name:"Disaster Recovery Services")
Category.create(oid: 12023, name:"Docks")
Category.create(oid: 12024, name:"Doors")
Category.create(oid: 12025, name:"Drywall & Plaster")
Category.create(oid: 12026, name:"Electrical")
Category.create(oid: 12028, name:"Excavation")
Category.create(oid: 12029, name:"Fans")
Category.create(oid: 12030, name:"Fences")
Category.create(oid: 12031, name:"Fireplace & Wood Stoves")
Category.create(oid: 15212, name:"Fitness & Sports Equipment Assembly")
Category.create(oid: 12032, name:"Flooring & Carpet")
Category.create(oid: 12033, name:"Foundations")
Category.create(oid: 12034, name:"Fountains & Ponds")
Category.create(oid: 15209, name:"Furniture Assembly")
Category.create(oid: 12035, name:"Furniture Repair & Refinish")
Category.create(oid: 12036, name:"Garage & Garage Doors")
Category.create(oid: 12037, name:"Glass & Mirrors")
Category.create(oid: 12038, name:"Gutters")
Category.create(oid: 12039, name:"Handyman Services")
Category.create(oid: 12040, name:"Heating & Furnace Systems")
Category.create(oid: 12041, name:"Home Inspection")
Category.create(oid: 12042, name:"Home Maintenance")
Category.create(oid: 12043, name:"Home Security Services")
Category.create(oid: 12044, name:"Hot Tubs, Spas & Saunas")
Category.create(oid: 15088, name:"Household Help")
Category.create(oid: 12045, name:"Insulation")
Category.create(oid: 12046, name:"Landscaping")
Category.create(oid: 12047, name:"Lawn & Garden Care")
Category.create(oid: 15211, name:"Lifting & Moving Heavy Items")
Category.create(oid: 12048, name:"Locksmith")
Category.create(oid: 12049, name:"Metal Fabrication")
Category.create(oid: 12072, name:"Mold & Asbestos Services")
Category.create(oid: 12050, name:"Moving")
Category.create(oid: 12051, name:"New Home Builders")
Category.create(oid: 12052, name:"Organizers")
Category.create(oid: 12053, name:"Outdoor Playgrounds")
Category.create(oid: 15208, name:"Packing & Unpacking Services")
Category.create(oid: 12054, name:"Painting")
Category.create(oid: 12055, name:"Paving")
Category.create(oid: 12056, name:"Permit Services")
Category.create(oid: 12057, name:"Pest Control")
Category.create(oid: 12058, name:"Plumbing")
Category.create(oid: 12059, name:"Powdercoating")
Category.create(oid: 14980, name:"Power Washing")
Category.create(oid: 12061, name:"Roofing")
Category.create(oid: 12062, name:"Sandblasting Service")
Category.create(oid: 12081, name:"Septic Tanks & Wells")
Category.create(oid: 12063, name:"Sheds & Enclosures")
Category.create(oid: 12064, name:"Siding")
Category.create(oid: 12065, name:"Sign Making Service")
Category.create(oid: 12066, name:"Skylights")
Category.create(oid: 12067, name:"Snow Removal Service")
Category.create(oid: 14820, name:"Solar")
Category.create(oid: 12068, name:"Stained Glass")
Category.create(oid: 12070, name:"Swimming Pools")
Category.create(oid: 12071, name:"Tennis or Game Court")
Category.create(oid: 12073, name:"Tile")
Category.create(oid: 12074, name:"Tree Service")
Category.create(oid: 12075, name:"Wall Coverings")
Category.create(oid: 12076, name:"Waste Material Removal")
Category.create(oid: 12077, name:"Water Treatment System")
Category.create(oid: 12078, name:"Waterproofing")
Category.create(oid: 12079, name:"Window Coverings")
Category.create(oid: 12080, name:"Windows")
Category.create(oid: 15210, name:"Yard & Garden Work")
